In [1]:
import os
import pandas as pd
import random
random.seed(1)

# 2015

(i) Get data

In [2]:
#read in the dataset
brfss_2015_dataset = pd.read_csv('2015.csv')

In [3]:
#how many rows and columns
brfss_2015_dataset.shape

(441456, 330)

In [4]:
pd.set_option('display.max_columns', 500)
brfss_2015_dataset.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,IMFVPLAC,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,PAINACT2,QLMENTL2,QLSTRES2,QLHLTH2,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,VIDFCLT2,VIREDIF3,VIPRFVS2,VINOCRE2,VIEYEXM2,VIINSUR2,VICTRCT4,VIGLUMA2,VIMACDG2,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,TETANUS,HPVADVC2,HPVADSHT,SHINGLE2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PROFEXAM,LENGEXAM,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SXORIENT,TRNSGNDR,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,ADPLEASR,ADDOWN,ADSLEEP,ADENERGY,ADEAT1,ADFAIL,ADTHINK,ADMOVE,MISTMNT,ADANXEV,QSTVER,QSTLANG,EXACTOT1,EXACTOT2,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,FTJUDA1_,FRUTDA1_,BEANDAY_,GRENDAY_,ORNGDAY_,VEGEDA1_,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRUTSUM,_VEGESUM,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,1,1,b'01292015',b'01',b'29',b'2015',1200,2015000001,2015000001,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,15.0,18,10.0,1,1,2.0,1.0,1.0,1.0,1,1.0,1.0,2,2.0,2,1,1.0,2.0,2,1,1.0,1,2,3.0,NaN,2,1,4,1,2.0,NaN,1.0,2.0,8,88.0,3.0,2.0,280.0,510.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,305.0,310.0,320.0,310.0,305.0,101.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,6.0,1.0,1.0,112014.0,1.0,1.0,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,b'',b'',3.0,11011,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1,0.614125,341.384853,2,1,2,1,2.0,2.0,2,2,1,1.0,1,1,2,1,1,1,1.0,9,1,63,5,70.0,178.0,12701.0,4018.0,4.0,2,1,2,2,3,1,2,5.400000e-79,1,5.400000e-79,1,1.700000e+01,33.0,6.700000e+01,33.0,17.0,100.0,5.400000e-79,5.400000e-79,1.000000e+00,1.000000e+00,50.0,217.0,2,1,1.0,1.0,5.400000e-79,5.400000e-79,2,NaN,NaN,2469,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.400000e-79,5.400000e-79,NaN,NaN,NaN,NaN,NaN,NaN,4,2,3,3,2,2,4,2,1.0,1.0,1.0,1,1,NaN,NaN,1.0
1,1,1,b'01202015',b'01',b'20',b'2015',1100,2015000002,2015000002,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.400000e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88,NaN,2,1,1.0,4.0,3.0,NaN,1,4.0,2.0,2,2.0,2,2,NaN,2.0,2,2,2.0,2,2,3.0,NaN,2,2,6,1,2.0,NaN,2.0,2.0,3,88.0,1.0,1.0,165.0,508.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,302.0,305.0,302.0,202.0,202.0,304.0,1.0,64.0,212.0,100.0,69.0,212.0,100.0,888.0,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,NaN,5.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',1.0,2.0,NaN,NaN,2.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,b'',b'',5.0,11011,28.78156,1.0,28.781560,NaN,NaN,NaN,NaN,9,NaN,108.060903,1,2,1,2,1.0,2.0,1,1,3,2.0,1,1,2,1,1,1,1.0,7,1,52,4,68.0,173.0,7484.0,2509.0,3.0,2,1,4,1,1,2,2,5.400000e-79,1,5.400000e-79,1,7.000000e+00,17.0,7.000000e+00,29.0,29.0,13.0,5.400000e-79,5.400000e-79,1.000000e+00,1.000000e+00,24.0,78.0,2,2,1.0,1.0,5.400000e-79,5.400000e-79,1,35.0,5.400000e-79,2876,493,1.0,5.400000e-79,60.0,60.0,2800.0,2800.0,168.0,5.400000e-79,5.400000e-79,5.400000e-79,168.0,5.400000e-79,168.0,5.400000e-79,5.400000e-79,5.400000e-79,2,1,1,2,2,2,2,2,3.0,3.0,4.0,2,2,NaN,NaN,2.0
2,1,1,b'02012015',b'02',b'01',b'2015',1200,2015000003,2015000003,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,15.0,88,88.0,1,2,2.0,1.0,3.0,NaN,1,1.0,1.0,7,2.0,1,2,NaN,2.0,1,2,1.0,2,2,3.0,NaN,2,2,4,1,2.0,NaN,1.0,2.0,7,88.0,99.0,2.0,158.0,511.0,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,b'',b'',5.0,11011,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,1,0.614125,255.264796,2,9,1,1,2.0,NaN,1,1,3,1.0,1,1,2,1,1,1,1.0,11,2,71,6,71.0,180.0,7167.0,2204.0,2.0,1,1,2,9,9,9,9,9.000000e+02,9,9.990000e+04,9,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,4.000000e+00,5.400000e-79,5.400000e-79,NaN,NaN,9,9,1.0,1.0,1.000000e+00,1.000000e+00,9,NaN,NaN,2173,373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9,9,9,9,9,9,9,9,9.0,9.0,9.0,9,9,9.0,9.0,NaN
3,1,1,b'01142015',b'01',b'14',b'2015',1100,2015000004,2015000004,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,30.0,30,30.0,1,2,1.0,1.0,1.0,1.0,1,1.0,1.0,2,2.0,2,2,NaN,2.0,1,2,1.0,1,2,3.0,NaN,2,1,4,1,2.0,NaN,1.0,2.0,8,1.0,8.0,2.0,180.0,507.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,555.0,101.0,555.0,301.0,301.0,201.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,8.0,1.0,1.0,777777.0,5.0,1.0,9.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',4.0,7.0,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,b'',b'',3.0,11011,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1,0.614125,341.384853,2,1,2,1,2.0,2.0,1,1,3,1.0,1,1,2,1,1,1,1.0,9,1,63,5,67.0,170.0,8165.0,2819.0,3.0,2,2,2,5,4,1,2,5.400000e-79,1,5.400000e-79,1,5.400000e-79,100.0,5.400000e-79,3.0,3.0,14.0,5.400000e-79,5.400000e-79,1.000000e+00,1.000000e+00,100.0,20.0,1,2,1.0,1.0,5.400000e-79,5.400000e-79,2,NaN,NaN,2469,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.400000e-79,5.400000e-79,NaN,NaN,NaN,NaN,NaN,NaN,4,2,3,3,2,2,4,2,1.0,1.0,1.0,1,1,NaN,NaN,9.0
4,1,1,b'01142015',b'01',b'14',b'2015',1100,2015000005,2015000005,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,20.0,88,30.0,1,1,2.0,1.0,3.0,NaN,1,1.0,2.0,2,2.0,2,2,NaN,2.0,2,2,1.0,2,2,3.0,NaN,2,1,5,1,2.0,NaN,2.0,2.0,8,88.0,77.0,1.0,142.0,504.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,777.0,102.0,203.0,204.0,310.0,320.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,NaN,1.0,1.0,777777.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,5.0,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,b'',b'',3.0,11011,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,9,NaN,258.682223,2,1,1,1,1.0,2.0,1,1,3,1.0,1,1,2,1,1,1,1.0,9,1,61,5,64.0,163.0,6441.0,2437.0,2.0,1,1,3,9,4,1,2,5.400000e-79,1,5.400000e-79,1,NaN,200.0,4.300000e+01,57.0,33.0,67.0,1.000000e+00,5.400000e-79,5.400000e-79,1.000000e+00,NaN,200.0,9,1,1.0,1.0,1.000000e+00,5.400000e-79,2,NaN,NaN,2543,436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.400000e-79,5.400000e-79,NaN,NaN,NaN,NaN,NaN,NaN,4,2,3,3,2,2,4,2,1.0,1.0,1.0,1,1,NaN,NaN,1.0

In [5]:
# select specific columns
brfss_2015_df_selected = brfss_2015_dataset[['CVDINFR4', 'CVDCRHD4',
                                             '_RFHYPE5', 'TOLDHI2',
                                             '_CHOLCHK',
                                             '_BMI5', 
                                             'SMOKE100', 
                                             'CVDSTRK3', 'DIABETE3', 
                                             '_TOTINDA',  
                                             'ALCDAY5', 'AVEDRNK2', 'DROCDY3_',
                                             'HLTHPLN1', 'MEDCOST', '_DRNKWEK',
                                             'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 
                                             'SEX', '_AGEG5YR', 'EDUCA', 'INCOME2',
                                             '_STATE', '_MICHD', '_RFDRHV5', 
                                            ]]

In [6]:
brfss_2015_df_selected.shape

(441456, 26)

In [7]:
brfss_2015_df_selected.head()

,CVDINFR4,CVDCRHD4,_RFHYPE5,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,DIABETE3,_TOTINDA,ALCDAY5,AVEDRNK2,DROCDY3_,HLTHPLN1,MEDCOST,_DRNKWEK,GENHLTH,MENTHLTH,PHYSHLTH,SEX,_AGEG5YR,EDUCA,INCOME2,_STATE,_MICHD,_RFDRHV5
0,2,2.0,2,1.0,1,4018.0,1.0,2,3.0,2,888.0,NaN,5.400000e-79,1,2.0,5.400000e-79,5.0,18,15.0,2,9,4,3.0,1,2.0,1
1,2,2.0,1,2.0,2,2509.0,1.0,2,3.0,1,888.0,NaN,5.400000e-79,2,1.0,5.400000e-79,3.0,88,88.0,2,7,6,1.0,1,2.0,1
2,7,2.0,1,1.0,1,2204.0,NaN,1,3.0,9,NaN,NaN,9.000000e+02,1,2.0,9.990000e+04,4.0,88,15.0,2,11,4,99.0,1,NaN,9
3,2,2.0,2,1.0,1,2819.0,2.0,2,3.0,2,888.0,NaN,5.400000e-79,1,1.0,5.400000e-79,5.0,30,30.0,2,9,4,8.0,1,2.0,1
4,2,2.0,1,2.0,1,2437.0,2.0,2,3.0,2,888.0,NaN,5.400000e-79,1,2.0,5.400000e-79,5.0,88,20.0,2,9,5,77.0,1,2.0,1

(iii) Clean data

In [8]:
#drop rows with missing values
brfss_2015_df_selected = brfss_2015_df_selected.dropna()
brfss_2015_df_selected.shape

(174066, 26)

Variable: _MICHD
Description: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)

    1 -> Reported having MI or CHD
    2 -> Did not report having MI or CHD

Changing 2 to 0 to represent No

In [9]:
brfss_2015_df_selected['_MICHD'] = brfss_2015_df_selected['_MICHD'].replace({2: 0})
brfss_2015_df_selected._MICHD.unique()

array([0., 1.])

Variable: _RFHYPE5
Description: Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional
    
    1 -> No
    2 -> Yes  
    9 -> Don't know/Not sure/Refused/Missing
    
Changing 1 to 0 to represent No
Changing 2 to 1 to represent Yes
Dropping 9

In [10]:
brfss_2015_df_selected['_RFHYPE5'] = brfss_2015_df_selected['_RFHYPE5'].replace({1:0, 2:1})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected._RFHYPE5 != 9]
brfss_2015_df_selected._RFHYPE5.unique()

array([1, 0], dtype=int64)

Variable: TOLDHI2
Description: Have you EVER been told by a doctor, nurse or other health professional that your blood cholesterol is high?
    
    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [11]:
brfss_2015_df_selected['TOLDHI2'] = brfss_2015_df_selected['TOLDHI2'].replace({2:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.TOLDHI2 != 7]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.TOLDHI2 != 9]
brfss_2015_df_selected.TOLDHI2.unique()

array([1., 0.])

Variable: _CHOLCHK
Description: Have you EVER been told by a doctor, nurse or other health professional that your blood cholesterol is high?
    
    1 -> Had cholesterol checked in past 5 years
    2 -> Did not have cholesterol checked in past 5 years
    3 -> Have never had cholesterol checked
    9 -> Don’t know/Not Sure Or Refused/Missing
    
Changing 3 to 0 and 2 to 0 to represent 'did not have cholesterol checked in past 5 years'
Dropping 9

In [12]:
brfss_2015_df_selected['_CHOLCHK'] = brfss_2015_df_selected['_CHOLCHK'].replace({3:0,2:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected._CHOLCHK != 9]
brfss_2015_df_selected._CHOLCHK.unique()

array([1, 0], dtype=int64)

Variable: _BMI5
Description: Body Mass Index (BMI) * 100
    
Adjusting values to get actual BMI

In [13]:
brfss_2015_df_selected['_BMI5'] = brfss_2015_df_selected['_BMI5'].div(100).round(0)
brfss_2015_df_selected._BMI5.unique()

array([24., 25., 26., 28., 33., 23., 41., 27., 31., 30., 21., 22., 19.,
       34., 38., 18., 29., 36., 32., 35., 37., 49., 40., 20., 16., 17.,
       47., 39., 50., 45., 46., 42., 44., 52., 59., 15., 51., 55., 43.,
       54., 48., 56., 74., 62., 14., 13., 53., 73., 58., 84., 61., 65.,
       79., 60., 68., 66., 67., 71., 64., 72., 57., 92., 88., 82., 96.,
       81., 63., 77., 95., 75., 91., 69., 87., 70., 89., 98., 12., 78.,
       80., 83., 76.])

Variable: SMOKE100
Description: Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes]

    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [14]:
brfss_2015_df_selected['SMOKE100'] = brfss_2015_df_selected['SMOKE100'].replace({2:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.SMOKE100 != 7]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.SMOKE100 != 9]
brfss_2015_df_selected.SMOKE100.unique()

array([0., 1.])

Variable: CVDSTRK3
Description: (Ever told) you had a stroke?

    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [15]:
brfss_2015_df_selected['CVDSTRK3'] = brfss_2015_df_selected['CVDSTRK3'].replace({2:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.CVDSTRK3 != 7]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.CVDSTRK3 != 9]
brfss_2015_df_selected.CVDSTRK3.unique()

array([0, 1], dtype=int64)

Variable: DIABETE3
Description: (Ever told) you have diabetes?

    1 -> Yes
    2 -> Yes, but female told only during pregnancy
    3 -> No
    4 -> No, pre-diabetes or borderline diabetes
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Making it ordinal - changing 2 to 0 and 3 to 0 to represent 'no diabetes or only during pregnancy'
                    changing 4 to 1 to represent prediabetes or borderline diabetes
                    changing 1 to 2 to represent diabetes
Dropping 7 and 9

In [16]:
brfss_2015_df_selected['DIABETE3'] = brfss_2015_df_selected['DIABETE3'].replace({2:0, 3:0, 1:2, 4:1})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.DIABETE3 != 7]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.DIABETE3 != 9]
brfss_2015_df_selected.DIABETE3.unique()

array([0., 2., 1.])

Variable: _TOTINDA
Description: Adults that report doing physical activity or exercise during the past 30 days other than their regular job
    
    1 -> Had physical activity or exercise
    2 -> No physical activity or exercise in last 30 days  
    9 -> Don’t know/Refused/Missing
    
Changing 2 to 0 to represent No physical activity or exercise in last 30 days 
Dropping 9

In [17]:
brfss_2015_df_selected['_TOTINDA'] = brfss_2015_df_selected['_TOTINDA'].replace({2:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected._TOTINDA != 9]
brfss_2015_df_selected._TOTINDA.unique()

array([1, 0], dtype=int64)

Variable: _RFDRHV5
Description: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per
week)
    
    1 -> No
    2 -> Yes  
    9 -> Don’t know/Refused/Missing
    
Changing 1 to 0 to represent No
Changing 2 to 1 to represent Yes
Dropping 9

In [18]:
brfss_2015_df_selected['_RFDRHV5'] = brfss_2015_df_selected['_RFDRHV5'].replace({1.0:0, 2:1})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected._RFDRHV5 != 9]
# brfss_2015_df_selected._RFDRHV5.unique()

Variable: HLTHPLN1
Description: Do you have any kind of health care coverage, including health insurance, prepaid plans such as HMOs, or
government plans such as Medicare, or Indian Health Service?
    
    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [19]:
brfss_2015_df_selected['HLTHPLN1'] = brfss_2015_df_selected['HLTHPLN1'].replace({2:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.HLTHPLN1 != 7]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.HLTHPLN1 != 9]
brfss_2015_df_selected.HLTHPLN1.unique()

array([1, 0], dtype=int64)

Variable: MEDCOST
Description: Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?
    
    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [20]:
brfss_2015_df_selected['MEDCOST'] = brfss_2015_df_selected['MEDCOST'].replace({2:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.MEDCOST != 7]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.MEDCOST != 9]
brfss_2015_df_selected.MEDCOST.unique()

array([0., 1.])

Variable: GENHLTH
Description: Would you say that in general your health is:
    
    1 -> Excellent
    2 -> Very good
    3 -> Good
    4 -> Fair
    5 -> Poor
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Keeping it ordinal
Dropping 7 and 9

In [21]:
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.GENHLTH != 7]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.GENHLTH != 9]
brfss_2015_df_selected.GENHLTH.unique()

array([2., 3., 4., 1., 5.])

Variable: MENTHLTH
Description: Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how
many days during the past 30 days was your mental health not good?
    
    1 - 30 -> Number of days
              Notes: _ _ Number of days
        88 -> None 
        77 -> Don’t know/Not sure    
        99 -> Refused
    
Changing 88 to 0 to represent no bad mental health days
Dropping 77 and 99

In [22]:
brfss_2015_df_selected['MENTHLTH'] = brfss_2015_df_selected['MENTHLTH'].replace({88:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.MENTHLTH != 77]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.MENTHLTH != 99]
brfss_2015_df_selected.MENTHLTH.unique()

array([ 3,  0,  5, 15, 10, 20, 30,  1, 29,  2,  4,  9,  7, 21, 14, 25,  6,
       11, 12,  8, 24, 13, 27, 28, 16, 18, 17, 23, 19, 22, 26],
      dtype=int64)

Variable: PHYSHLTH
Description: Now thinking about your physical health, which includes physical illness and injury, for how many days during the
past 30 days was your physical health not good?
    
    1 - 30 -> Number of days
              Notes: _ _ Number of days
        88 -> None 
        77 -> Don’t know/Not sure    
        99 -> Refused
    
Changing 88 to 0 to represent no bad physical health days
Dropping 77 and 99

In [23]:
brfss_2015_df_selected['PHYSHLTH'] = brfss_2015_df_selected['PHYSHLTH'].replace({88:0})
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.PHYSHLTH != 77]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.PHYSHLTH != 99]
brfss_2015_df_selected.PHYSHLTH.unique()

array([ 0., 15.,  7., 20.,  1.,  3.,  5., 30.,  4.,  6.,  2., 14.,  8.,
       25., 10., 21., 12., 28., 18., 13., 27., 23.,  9., 17., 29., 11.,
       16., 24., 19., 26., 22.])

Variable: SEX
Description: Indicate sex of respondent
    
   1 -> Male
   2 -> Female
    
Changing 2 to 0 to represent female

In [24]:
brfss_2015_df_selected['SEX'] = brfss_2015_df_selected['SEX'].replace({2:0})
brfss_2015_df_selected.SEX.unique()

array([0, 1], dtype=int64)

Variable: _AGEG5YR
Description: Fourteen-level age category
    
   1 -> Age 18 to 24
   2 -> Age 25 to 29
   3 -> Age 30 to 34
   4 -> Age 35 to 39
   5 -> Age 40 to 44
   6 -> Age 45 to 49
   7 -> Age 50 to 54
   8 -> Age 55 to 59
   9 -> Age 60 to 64
   10 -> Age 65 to 69
   11 -> Age 70 to 74
   12 -> Age 75 to 79
   13 -> Age 80 or older
   14 -> Don’t know/Refused/Missing
    
Dropping 14

In [25]:
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected._AGEG5YR != 14]
brfss_2015_df_selected._AGEG5YR.unique()

array([11, 13,  7,  6,  2,  4,  5, 10,  8,  9, 12,  3,  1], dtype=int64)

Variable: EDUCA
Description: What is the highest grade or year of school you completed?
    
   1 -> Never attended school or only kindergarten
   2 -> Grades 1 through 8 (Elementary)
   3 -> Grades 9 through 11 (Some high school)
   4 -> Grade 12 or GED (High school graduate)
   5 -> College 1 year to 3 years (Some college or technical school)
   6 -> College 4 years or more (College graduate)
   9 -> Refused
    
Dropping 9

In [26]:
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.EDUCA != 9]
brfss_2015_df_selected.EDUCA.unique()

array([5, 4, 6, 3, 2, 1], dtype=int64)

Variable: INCOME2
Description: Is your annual household income from all sources:
    
   1 -> Less than $10,000
   2 -> Less than $15,000 ($10,000 to less than $15,000)
   3 -> Less than $20,000 ($15,000 to less than $20,000)
   4 -> Less than $25,000 ($20,000 to less than $25,000)
   5 -> Less than $35,000 ($25,000 to less than $35,000)
   6 -> Less than $50,000 ($35,000 to less than $50,000)
   7 -> Less than $75,000 ($50,000 to less than $75,000)
   8 -> $75,000 or more
   77 -> Don't know/Not sure
   99 -> Refused
    
Dropping 77 and 99

In [27]:
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.INCOME2 != 77]
brfss_2015_df_selected = brfss_2015_df_selected[brfss_2015_df_selected.INCOME2 != 99]
brfss_2015_df_selected.INCOME2.unique()

array([4., 8., 7., 6., 5., 2., 3., 1.])

In [28]:
brfss_2015_df_selected.shape

(140899, 26)

In [29]:
brfss_2015_df_selected.head()

,CVDINFR4,CVDCRHD4,_RFHYPE5,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,DIABETE3,_TOTINDA,ALCDAY5,AVEDRNK2,DROCDY3_,HLTHPLN1,MEDCOST,_DRNKWEK,GENHLTH,MENTHLTH,PHYSHLTH,SEX,_AGEG5YR,EDUCA,INCOME2,_STATE,_MICHD,_RFDRHV5
6,2,2.0,1,1.0,1,24.0,0.0,0,0.0,1,203.0,1.0,10.0,1,0.0,70.0,2.0,3,0.0,0,11,5,4.0,1,0.0,0
15,2,2.0,1,1.0,1,25.0,1.0,0,0.0,1,202.0,2.0,7.0,1,0.0,93.0,3.0,0,0.0,0,11,4,4.0,1,0.0,0
21,2,2.0,0,0.0,1,25.0,1.0,0,2.0,1,201.0,1.0,3.0,1,0.0,23.0,3.0,0,0.0,1,13,6,8.0,1,0.0,0
31,2,2.0,0,0.0,1,26.0,1.0,0,0.0,0,202.0,1.0,7.0,1,0.0,47.0,3.0,0,15.0,0,7,5,7.0,1,0.0,0
33,2,2.0,1,1.0,1,28.0,0.0,0,2.0,0,201.0,1.0,3.0,1,0.0,23.0,4.0,0,0.0,0,11,4,6.0,1,0.0,0

In [30]:
brfss_2015_df_selected.groupby(['_MICHD']).size()

_MICHD
0.0    131126
1.0      9773
dtype: int64

In [31]:
brfss_2015_df_selected.groupby(['DIABETE3']).size()

DIABETE3
0.0    126391
1.0      2104
2.0     12404
dtype: int64

In [32]:
#Rename the columns to make them more readable
brfss_2015_df_selected.rename(columns = {'_MICHD':'HeartDiseaseorAttack', 
                                         '_RFHYPE5':'HighBP',  
                                         'TOLDHI2':'HighChol', '_CHOLCHK':'CholCheck', 
                                         '_BMI5':'BMI', 
                                         'SMOKE100':'Smoker', 
                                         'CVDSTRK3':'Stroke', 'DIABETE3':'Diabetes', 
                                         '_TOTINDA':'PhysActivity',
                                         '_RFDRHV5':'HvyAlcoholConsump', 
                                         'HLTHPLN1':'AnyHealthcare', 'MEDCOST':'NoDocbcCost', 
                                         'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 
                                         'SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME2':'Income',
                                         '_STATE':'State', 'CVDINFR4':'HeartAttack', 'CVDCRHD4':'CoronaryHeartDisease',
                                         'ALCDAY5':'AtLeastOneDrinkPerWeekOrMonth', 'AVEDRNK2':'AvgDrinkPerDayInLastMonth',
                                         'DROCDY3_':'DrinkOccasionsPerDay', '_DRNKWEK':'DrinksPerWeek'
                                        }, inplace=True)

In [33]:
brfss_2015_df_selected.to_csv('2015cleaneddata.csv', sep=",", index=False)