In [1]:
import os
import pandas as pd
import random
random.seed(1)

# 2013

(i) Get data

In [2]:
#read in the dataset
brfss_2013_dataset = pd.read_csv('2013.csv')

In [3]:
#how many rows and columns
brfss_2013_dataset.shape

(491773, 336)

In [4]:
pd.set_option('display.max_columns', 500)
brfss_2013_dataset.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,SLEPTIM1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,VETERAN3,MARITAL,CHILDREN,EDUCA,EMPLOY1,INCOME2,WEIGHT2,HEIGHT3,NUMHHOL2,NUMPHON2,CPDEMO1,CPDEMO4,INTERNET,RENTHOM1,SEX,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,TETANUS,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,DIABAGE2,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,PAINACT2,QLMENTL2,QLSTRES2,QLHLTH2,MEDICARE,HLTHCVRG,DELAYMED,DLYOTHER,NOCOV121,LSTCOVRG,DRVISITS,MEDSCOST,CARERCVD,MEDBILLS,SSBSUGAR,SSBFRUT2,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,IMFVPLAC,HPVADVC2,HPVADSHT,HADMAM,HOWLONG,PROFEXAM,LENGEXAM,HADPAP2,LASTPAP2,HADHYST2,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,RRCLASS2,RRCOGNT2,RRATWRK2,RRHCARE3,RRPHYSM2,RREMTSM2,MISNERVS,MISHOPLS,MISRSTLS,MISDEPRD,MISEFFRT,MISWTLES,MISNOWRK,MISTMNT,MISTRHLP,MISPHLPF,SCNTMONY,SCNTMEAL,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SCNTVOT1,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,PCTCELL,QSTVER,QSTLANG,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_IMPNPH,_CHISPNC,_CRACE1,_IMPCAGE,_IMPCRAC,_IMPCSEX,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKDY4,_DRNKMO4,_RFDRHV4,_RFDRMN4,_RFDRWM4,FTJUDA1_,FRUTDA1_,BEANDAY_,GRENDAY_,ORNGDAY_,VEGEDA1_,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRUTSUM,_VEGESUM,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3,_AGE80,_IMPEDUC,_IMPMRTL,_IMPHOME,RCSBRAC1,RCSRACE1,RCHISLA1,RCSBIRTH,TYPEINDS,TYPEWORK
0,1.0,1.0,b'01092013',b'01',b'09',b'2013',1100.0,2.013001e+09,2.013001e+09,1.0,1.0,NaN,1.0,1.0,NaN,2.0,1.0,1.0,4.0,30.0,29.0,30.0,1.0,1.0,2.0,1.0,77.0,1.0,1.0,1.0,1.0,1.0,2.0,7.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,2.0,2.0,88.0,6.0,7.0,7.0,250.0,507.0,1.0,2.0,1.0,10.0,1.0,1.0,2.0,NaN,1.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,3.0,NaN,7.0,3.0,201.0,2.0,88.0,2.0,304.0,104.0,303.0,310.0,303.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,4.0,1.0,2.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,3.0,11081.0,40.197675,1.0,40.197675,2.0,2.0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,331.493357,238.016092,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,9.0,1.0,5.0,67.0,170.0,11340.0,3916.0,4.0,2.0,1.0,4.0,5.0,3.0,1.0,1.0,3.000000e+00,1.0,7.000000e+00,2.000000e+00,1.0,NaN,1.0,1.300000e+01,400.0,10.0,33.0,10.0,NaN,5.397605e-79,1.000000e+00,1.0,5.397605e-79,413.0,NaN,1.0,9.0,1.0,1.0,5.397605e-79,1.000000e+00,2.0,NaN,NaN,2580.0,442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,60.0,6.0,2.0,1.0,NaN,b'',b'',b'',b'',b''
1,1.0,1.0,b'01192013',b'01',b'19',b'2013',1100.0,2.013001e+09,2.013001e+09,1.0,1.0,NaN,1.0,1.0,NaN,2.0,1.0,1.0,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,6.0,3.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,1.0,2.0,5.0,1.0,8.0,127.0,510.0,2.0,NaN,1.0,70.0,1.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,305.0,301.0,310.0,203.0,202.0,203.0,1.0,64.0,105.0,20.0,73.0,101.0,10.0,888.0,NaN,NaN,NaN,NaN,1.0,1.0,102012.0,1.0,2.0,1.0,777777.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,3.0,11081.0,40.197675,2.0,80.395350,1.0,1.0,2.0,1.0,3.0,1.0,2.0,954.078239,9.0,NaN,662.986714,737.694204,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,4.0,70.0,178.0,5761.0,1822.0,1.0,1.0,3.0,3.0,5.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,5.397605e-79,1.0,NaN,1.0,1.700000e+01,3.0,33.0,43.0,29.0,43.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,20.0,148.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,35.0,3.300000e+01,2950.0,506.0,1.0,1.000000e+00,20.0,10.0,5000.0,1000.0,100.0,1.000000e+01,5.397605e-79,5.397605e-79,100.0,1.000000e+01,110.0,5.397605e-79,5.397605e-79,5.397605e-79,3.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,3.0,3.0,4.0,1.0,1.0,NaN,NaN,1.0,50.0,5.0,1.0,1.0,NaN,b'',b'',b'',b'',b''
2,1.0,1.0,b'01192013',b'01',b'19',b'2013',1100.0,2.013001e+09,2.013001e+09,1.0,1.0,NaN,1.0,1.0,NaN,3.0,2.0,1.0,3.0,3.0,2.0,88.0,1.0,1.0,2.0,1.0,9.0,3.0,NaN,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,2.0,3.0,2.0,1.0,88.0,6.0,1.0,8.0,160.0,504.0,2.0,NaN,1.0,70.0,1.0,1.0,2.0,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,NaN,3.0,220.0,4.0,20.0,10.0,301.0,203.0,202.0,202.0,310.0,330.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,2.0,5.0,1.0,1.0,12013.0,1.0,2.0,1.0,777777.0,7.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,3.0,11081.0,40.197675,3.0,120.593025,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,994.480071,568.527386,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,8.0,1.0,5.0,64.0,163.0,7257.0,2746.0,3.0,2.0,1.0,4.0,5.0,2.0,2.0,1.0,6.700000e+01,2.0,2.670000e+02,8.000000e+01,2.0,NaN,2.0,3.000000e+00,43.0,29.0,29.0,33.0,100.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,46.0,191.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2765.0,474.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,2.0,1.0,1.0,NaN,NaN,1.0,55.0,6.0,1.0,1.0,NaN,b'',b'',b'',b'',b''
3,1.0,1.0,b'01112013',b'01',b'11',b'2013',1100.0,2.013001e+09,2.013001e+09,1.0,1.0,NaN,1.0,1.0,NaN,2.0,1.0,1.0,2.0,2.0,88.0,88.0,1.0,1.0,2.0,2.0,8.0,3.0,NaN,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,88.0,4.0,7.0,7.0,128.0,504.0,2.0,NaN,1.0,75.0,1.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,208.0,2.0,88.0,2.0,202.0,306.0,202.0,310.0,305.0,204.0,1.0,64.0,205.0,30.0,88.0,NaN,NaN,888.0,NaN,NaN,NaN,NaN,1.0,2.0,NaN,4.0,2.0,2.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,3.0,11081.0,40.197675,2.0,80.395350,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,662.986714,606.976365,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,5.0,64.0,163.0,5806.0,2197.0,2.0,1.0,1.0,2.0,5.0,4.0,1.0,1.0,2.700000e+01,1.0,5.300000e+01,1.600000e+01,1.0,NaN,1.0,2.900000e+01,20.0,29.0,33.0,17.0,57.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,49.0,136.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,35.0,5.397605e-79,2432.0,417.0,1.0,5.397605e-79,30.0,NaN,1167.0,NaN,35.0,5.397605e-79,5.397605e-79,5.397605e-79,35.0,5.397605e-79,35.0,5.397605e-79,5.397605e-79,5.397605e-79,3.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,3.0,3.0,4.0,1.0,1.0,NaN,NaN,2.0,64.0,4.0,1.0,1.0,NaN,b'',b'',b'',b'',b''
4,1.0,2.0,b'02062013',b'02',b'06',b'2013',1100.0,2.013001e+09,2.013001e+09,1.0,1.0,NaN,1.0,1.0,NaN,2.0,1.0,1.0,3.0,10.0,2.0,88.0,1.0,1.0,2.0,4.0,6.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,88.0,6.0,7.0,6.0,265.0,600.0,2.0,NaN,1.0,888.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,1.0,3.0,210.0,2.0,88.0,3.0,555.0,302.0,101.0,310.0,303.0,101.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,NaN,NaN,NaN,NaN,1.0,2.0,NaN,4.0,2.0,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,3.0,11082.0,60.319184,2.0,120.638368,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,994.853994,629.847064,1.0,9.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,10.0,2.0,6.0,72.0,183.0,12020.0,3594.0,4.0,2.0,1.0,4.0,4.0,3.0,1.0,1.0,3.300000e+01,1.0,6.700000e+01,2.000000e+01,1.0,1.0,NaN,5.397605e-79,7.0,100.0,33.0,10.0,100.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,7.0,243.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2370.0,406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,3.0,3.0,4.0,1.0,1.0,2.0,2.0,2.0,66.0,6.0,1.0,1.0,NaN,b'',b'',b'',b'',b''

In [5]:
# select specific columns
brfss_2013_df_selected = brfss_2013_dataset[['CVDINFR4', 'CVDCRHD4',
                                             '_RFHYPE5', 'TOLDHI2',
                                             '_CHOLCHK',
                                             '_BMI5', 
                                             'SMOKE100', 
                                             'CVDSTRK3', 'DIABETE3', 
                                             '_TOTINDA',  
                                             'ALCDAY5', 'AVEDRNK2',
                                             'HLTHPLN1', 'MEDCOST', 
                                             'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 
                                             'SEX', '_AGEG5YR', 'EDUCA', 'INCOME2',
                                             '_STATE'
                                            ]]

In [6]:
brfss_2013_df_selected.shape

(491773, 22)

In [7]:
brfss_2013_df_selected.head()

,CVDINFR4,CVDCRHD4,_RFHYPE5,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,DIABETE3,_TOTINDA,ALCDAY5,AVEDRNK2,HLTHPLN1,MEDCOST,GENHLTH,MENTHLTH,PHYSHLTH,SEX,_AGEG5YR,EDUCA,INCOME2,_STATE
0,2.0,7.0,2.0,1.0,1.0,3916.0,1.0,2.0,3.0,2.0,201.0,2.0,1.0,2.0,4.0,29.0,30.0,2.0,9.0,6.0,7.0,1.0
1,2.0,2.0,1.0,2.0,1.0,1822.0,2.0,2.0,3.0,1.0,888.0,NaN,1.0,2.0,3.0,88.0,88.0,2.0,7.0,5.0,8.0,1.0
2,2.0,2.0,1.0,2.0,2.0,2746.0,1.0,2.0,3.0,2.0,220.0,4.0,1.0,2.0,3.0,2.0,3.0,2.0,8.0,6.0,8.0,1.0
3,2.0,2.0,1.0,1.0,1.0,2197.0,2.0,2.0,3.0,1.0,208.0,2.0,1.0,2.0,2.0,88.0,2.0,2.0,9.0,4.0,7.0,1.0
4,2.0,2.0,2.0,2.0,1.0,3594.0,1.0,2.0,3.0,2.0,210.0,2.0,1.0,2.0,3.0,2.0,10.0,1.0,10.0,6.0,6.0,1.0

(ii) Calculate missing variables

Our target variable, _MICHD, is present in the dataset for the year 2015 but needs to be calculated based on existing variables for the year 2013.

Variable: _MICHD
Description: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)
    
    1 -> Reported having MI or CHD
         Notes: CVDINFR4=1 OR CVDCRHD4=1
    0 -> Did not report having MI or CHD
         Notes: CVDINFR4=2 AND CVDCRHD4=2

We will create this column.

In [8]:
# Create a new column '_MICHD' and calculate its values based on conditions
brfss_2013_df_selected['_MICHD'] = (brfss_2013_df_selected['CVDINFR4'] == 1) & (brfss_2013_df_selected['CVDCRHD4'] == 1)
# Convert True/False values to 1/0
brfss_2013_df_selected['_MICHD'] = brfss_2013_df_selected['_MICHD'].astype(int)

C:\Users\yumna\AppData\Local\Temp\ipykernel_30552\3559482575.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_2013_df_selected['_MICHD'] = (brfss_2013_df_selected['CVDINFR4'] == 1) & (brfss_2013_df_selected['CVDCRHD4'] == 1)
C:\Users\yumna\AppData\Local\Temp\ipykernel_30552\3559482575.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_2013_df_selected['_MICHD'] = brfss_2013_df_selected['_MICHD'].astype(int)

One feature, _RFDRHV5, is present in the dataset for the year 2015 but needs to be calculated based on existing variables for the year 2013.

Variable: _RFDRHV5
Description: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per
week)
    
      1 -> No
           Notes: SEX = 1 and _DRNKWEK <= 14 or SEX = 2 and _DRNKWEK <= 7 or ALCDAY5 = 888
      2 -> Yes
           Notes: SEX = 1 and _DRNKWEK > 14 or SEX = 2 and _DRNKWEK > 7
      9 -> Don’t know/Refused/Missing
           Notes: _DRNKWEK = 99900
    
This variable is calculated using two other columns DROCDY3_ and _DRNKWEK which ate also present in the dataset for the year 2015 but need to be calculated based on existing variables for the year 2013.

So first we will create the column DROCDY3_, then we will it use it to create _DRNKWEK. After that, we can use _DRNKWEK to create _RFDRHV5. For more details on the formulas behind the calculations, please see https://www.cdc.gov/brfss/annual_data/2015/pdf/2015_Calculated_Variables_Version4_08_10_17-508c.pdf

In [9]:
# Create a new column 'DROCDY3_' and initialize it with NaN values
brfss_2013_df_selected['DROCDY3_'] = float('nan')

# Apply the conditions and assign values to 'DROCDY3_'
brfss_2013_df_selected.loc[~brfss_2013_df_selected['ALCDAY5'].isin([888, 777, 999, pd.NaT]), 'DROCDY3_'] = brfss_2013_df_selected.loc[
    (brfss_2013_df_selected['ALCDAY5'].between(101, 107)), 'ALCDAY5'].sub(100).div(7)

brfss_2013_df_selected.loc[~brfss_2013_df_selected['ALCDAY5'].isin([888, 777, 999, pd.NaT]), 'DROCDY3_'] = brfss_2013_df_selected.loc[
    (brfss_2013_df_selected['ALCDAY5'].between(201, 230)), 'ALCDAY5'].sub(200).div(30)

brfss_2013_df_selected.loc[brfss_2013_df_selected['ALCDAY5'] == 888, 'DROCDY3_'] = 0
brfss_2013_df_selected.loc[~brfss_2013_df_selected['ALCDAY5'].isin([888, 777, 999, pd.NaT]), 'DROCDY3_'] = 9

C:\Users\yumna\AppData\Local\Temp\ipykernel_30552\1757789261.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_2013_df_selected['DROCDY3_'] = float('nan')

In [10]:
# Create a new column '_DRNKWEK' and initialize it with NaN values
brfss_2013_df_selected['_DRNKWEK'] = float('nan')

# Apply the conditions and assign values to '_DRNKWEK'
brfss_2013_df_selected.loc[brfss_2013_df_selected['DROCDY3_'] == 0, '_DRNKWEK'] = 0
brfss_2013_df_selected.loc[brfss_2013_df_selected['DROCDY3_'] == 9, '_DRNKWEK'] = 999
brfss_2013_df_selected.loc[brfss_2013_df_selected['AVEDRNK2'].isin([pd.NaT, 77, 99]), '_DRNKWEK'] = 999
brfss_2013_df_selected.loc[~brfss_2013_df_selected['AVEDRNK2'].isin([pd.NaT, 77, 99]), '_DRNKWEK'] = brfss_2013_df_selected['AVEDRNK2'] * brfss_2013_df_selected['DROCDY3_'] * 7

C:\Users\yumna\AppData\Local\Temp\ipykernel_30552\978326308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_2013_df_selected['_DRNKWEK'] = float('nan')

In [11]:
# Create a new column '_RFDRHV5' and initialize it with NaN values
brfss_2013_df_selected['_RFDRHV5'] = float('nan')

# Apply the conditions and assign values to '_RFDRHV5'
brfss_2013_df_selected.loc[(brfss_2013_df_selected['SEX'] == 1) & (~brfss_2013_df_selected['_DRNKWEK'].isin([999, pd.NaT])), '_RFDRHV5'] = \
    brfss_2013_df_selected.loc[(brfss_2013_df_selected['SEX'] == 1) & (~brfss_2013_df_selected['_DRNKWEK'].isin([999, pd.NaT])), '_DRNKWEK'].apply(lambda x: 2 if x > 14 else 1)

brfss_2013_df_selected.loc[(brfss_2013_df_selected['SEX'] == 2) & (~brfss_2013_df_selected['_DRNKWEK'].isin([999, pd.NaT])), '_RFDRHV5'] = \
    brfss_2013_df_selected.loc[(brfss_2013_df_selected['SEX'] == 2) & (~brfss_2013_df_selected['_DRNKWEK'].isin([999, pd.NaT])), '_DRNKWEK'].apply(lambda x: 2 if x > 7 else 1)

brfss_2013_df_selected.loc[brfss_2013_df_selected['ALCDAY5'] == 888, '_RFDRHV5'] = 1

brfss_2013_df_selected.loc[brfss_2013_df_selected['_DRNKWEK'].isin([999, pd.NaT]), '_RFDRHV5'] = 9

brfss_2013_df_selected._RFDRHV5.unique()

C:\Users\yumna\AppData\Local\Temp\ipykernel_30552\3764891815.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_2013_df_selected['_RFDRHV5'] = float('nan')

array([2., 1., 9.])

In [12]:
# Apply rounding to 'DROCDY3_' column
brfss_2013_df_selected['DROCDY3_'] = round(brfss_2013_df_selected['DROCDY3_'] * 100, 1)

# Apply rounding to '_DRNKWEK' column
brfss_2013_df_selected['_DRNKWEK'] = round(brfss_2013_df_selected['_DRNKWEK'] * 100, 1)

C:\Users\yumna\AppData\Local\Temp\ipykernel_30552\3273312710.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_2013_df_selected['DROCDY3_'] = round(brfss_2013_df_selected['DROCDY3_'] * 100, 1)
C:\Users\yumna\AppData\Local\Temp\ipykernel_30552\3273312710.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brfss_2013_df_selected['_DRNKWEK'] = round(brfss_2013_df_selected['_DRNKWEK'] * 100, 1)

(iii) Clean data

In [13]:
#drop rows with missing values
brfss_2013_df_selected = brfss_2013_df_selected.dropna()
brfss_2013_df_selected.shape

(196347, 26)

Variable: _MICHD
Description: Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)

    1 -> Reported having MI or CHD
    2 -> Did not report having MI or CHD

Changing 2 to 0 to represent No

In [14]:
brfss_2013_df_selected['_MICHD'] = brfss_2013_df_selected['_MICHD'].replace({2: 0})
brfss_2013_df_selected._MICHD.unique()

array([0, 1])

Variable: _RFHYPE5
Description: Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional
    
    1 -> No
    2 -> Yes  
    9 -> Don't know/Not sure/Refused/Missing
    
Changing 1 to 0 to represent No
Changing 2 to 1 to represent Yes
Dropping 9

In [15]:
brfss_2013_df_selected['_RFHYPE5'] = brfss_2013_df_selected['_RFHYPE5'].replace({1:0, 2:1})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected._RFHYPE5 != 9]
brfss_2013_df_selected._RFHYPE5.unique()

array([1., 0.])

Variable: TOLDHI2
Description: Have you EVER been told by a doctor, nurse or other health professional that your blood cholesterol is high?
    
    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [16]:
brfss_2013_df_selected['TOLDHI2'] = brfss_2013_df_selected['TOLDHI2'].replace({2:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.TOLDHI2 != 7]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.TOLDHI2 != 9]
brfss_2013_df_selected.TOLDHI2.unique()

array([1., 0.])

Variable: _CHOLCHK
Description: Have you EVER been told by a doctor, nurse or other health professional that your blood cholesterol is high?
    
    1 -> Had cholesterol checked in past 5 years
    2 -> Did not have cholesterol checked in past 5 years
    3 -> Have never had cholesterol checked
    9 -> Don’t know/Not Sure Or Refused/Missing
    
Changing 3 to 0 and 2 to 0 to represent 'did not have cholesterol checked in past 5 years'
Dropping 9

In [17]:
brfss_2013_df_selected['_CHOLCHK'] = brfss_2013_df_selected['_CHOLCHK'].replace({3:0,2:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected._CHOLCHK != 9]
brfss_2013_df_selected._CHOLCHK.unique()

array([1., 0.])

Variable: _BMI5
Description: Body Mass Index (BMI) * 100
    
Adjusting values to get actual BMI

In [18]:
brfss_2013_df_selected['_BMI5'] = brfss_2013_df_selected['_BMI5'].div(100).round(0)
brfss_2013_df_selected._BMI5.unique()

array([39., 27., 22., 36., 21., 30., 25., 28., 32., 29., 31., 24., 23.,
       34., 19., 20., 37., 42., 26., 33., 17., 35., 40., 53., 60., 38.,
       18., 49., 44., 43., 50., 46., 55., 47., 48., 65., 41., 15., 14.,
       52., 45., 63., 61., 16., 51., 66., 59., 54., 13., 58., 56., 74.,
       62., 57., 12., 68., 73., 72., 70., 67., 64., 80., 77., 86., 89.,
       69., 87., 71., 78., 79., 76.])

Variable: SMOKE100
Description: Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes]

    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [19]:
brfss_2013_df_selected['SMOKE100'] = brfss_2013_df_selected['SMOKE100'].replace({2:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.SMOKE100 != 7]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.SMOKE100 != 9]
brfss_2013_df_selected.SMOKE100.unique()

array([1., 0.])

Variable: CVDSTRK3
Description: (Ever told) you had a stroke?

    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [20]:
brfss_2013_df_selected['CVDSTRK3'] = brfss_2013_df_selected['CVDSTRK3'].replace({2:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.CVDSTRK3 != 7]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.CVDSTRK3 != 9]
brfss_2013_df_selected.CVDSTRK3.unique()

array([0., 1.])

Variable: DIABETE3
Description: (Ever told) you have diabetes?

    1 -> Yes
    2 -> Yes, but female told only during pregnancy
    3 -> No
    4 -> No, pre-diabetes or borderline diabetes
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Making it ordinal - changing 2 to 0 and 3 to 0 to represent 'no diabetes or only during pregnancy'
                    changing 4 to 1 to represent prediabetes or borderline diabetes
                    changing 1 to 2 to represent diabetes
Dropping 7 and 9

In [21]:
brfss_2013_df_selected['DIABETE3'] = brfss_2013_df_selected['DIABETE3'].replace({2:0, 3:0, 1:2, 4:1})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.DIABETE3 != 7]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.DIABETE3 != 9]
brfss_2013_df_selected.DIABETE3.unique()

array([0., 2., 1.])

Variable: _TOTINDA
Description: Adults that report doing physical activity or exercise during the past 30 days other than their regular job
    
    1 -> Had physical activity or exercise
    2 -> No physical activity or exercise in last 30 days  
    9 -> Don’t know/Refused/Missing
    
Changing 2 to 0 to represent No physical activity or exercise in last 30 days 
Dropping 9

In [22]:
brfss_2013_df_selected['_TOTINDA'] = brfss_2013_df_selected['_TOTINDA'].replace({2:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected._TOTINDA != 9]
brfss_2013_df_selected._TOTINDA.unique()

array([0., 1.])

Variable: _RFDRHV5
Description: Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per
week)
    
    1 -> No
    2 -> Yes  
    9 -> Don’t know/Refused/Missing
    
Changing 1 to 0 to represent No
Changing 2 to 1 to represent Yes
Dropping 9

In [23]:
brfss_2013_df_selected['_RFDRHV5'] = brfss_2013_df_selected['_RFDRHV5'].replace({1.0:0, 2:1})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected._RFDRHV5 != 9]
brfss_2013_df_selected._RFDRHV5.unique()

array([1.])

Variable: HLTHPLN1
Description: Do you have any kind of health care coverage, including health insurance, prepaid plans such as HMOs, or
government plans such as Medicare, or Indian Health Service?
    
    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [24]:
brfss_2013_df_selected['HLTHPLN1'] = brfss_2013_df_selected['HLTHPLN1'].replace({2:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.HLTHPLN1 != 7]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.HLTHPLN1 != 9]
brfss_2013_df_selected.HLTHPLN1.unique()

array([1., 0.])

Variable: MEDCOST
Description: Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?
    
    1 -> Yes
    2 -> No
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Changing 2 to 0 to represent No
Dropping 7 and 9

In [25]:
brfss_2013_df_selected['MEDCOST'] = brfss_2013_df_selected['MEDCOST'].replace({2:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.MEDCOST != 7]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.MEDCOST != 9]
brfss_2013_df_selected.MEDCOST.unique()

array([0., 1.])

Variable: GENHLTH
Description: Would you say that in general your health is:
    
    1 -> Excellent
    2 -> Very good
    3 -> Good
    4 -> Fair
    5 -> Poor
    7 -> Don’t know/Not sure    
    9 -> Refused
    
Keeping it ordinal
Dropping 7 and 9

In [26]:
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.GENHLTH != 7]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.GENHLTH != 9]
brfss_2013_df_selected.GENHLTH.unique()

array([4., 3., 2., 1., 5.])

Variable: MENTHLTH
Description: Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how
many days during the past 30 days was your mental health not good?
    
    1 - 30 -> Number of days
              Notes: _ _ Number of days
        88 -> None 
        77 -> Don’t know/Not sure    
        99 -> Refused
    
Changing 88 to 0 to represent no bad mental health days
Dropping 77 and 99

In [27]:
brfss_2013_df_selected['MENTHLTH'] = brfss_2013_df_selected['MENTHLTH'].replace({88:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.MENTHLTH != 77]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.MENTHLTH != 99]
brfss_2013_df_selected.MENTHLTH.unique()

array([29.,  2.,  0., 15.,  3.,  5., 10., 30.,  7.,  1., 21.,  4.,  6.,
       20., 25., 16., 14.,  8., 26., 18., 28., 27., 12., 24.,  9., 13.,
       11., 17., 19., 23., 22.])

Variable: PHYSHLTH
Description: Now thinking about your physical health, which includes physical illness and injury, for how many days during the
past 30 days was your physical health not good?
    
    1 - 30 -> Number of days
              Notes: _ _ Number of days
        88 -> None 
        77 -> Don’t know/Not sure    
        99 -> Refused
    
Changing 88 to 0 to represent no bad physical health days
Dropping 77 and 99

In [28]:
brfss_2013_df_selected['PHYSHLTH'] = brfss_2013_df_selected['PHYSHLTH'].replace({88:0})
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.PHYSHLTH != 77]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.PHYSHLTH != 99]
brfss_2013_df_selected.PHYSHLTH.unique()

array([30.,  3.,  2., 10.,  1.,  0.,  4., 14., 20.,  5., 15., 25., 28.,
        7., 12., 22., 21.,  8.,  6., 26., 19.,  9., 27., 29., 13., 18.,
       17., 23., 16., 24., 11.])

Variable: SEX
Description: Indicate sex of respondent
    
   1 -> Male
   2 -> Female
    
Changing 2 to 0 to represent female

In [29]:
brfss_2013_df_selected['SEX'] = brfss_2013_df_selected['SEX'].replace({2:0})
brfss_2013_df_selected.SEX.unique()

array([0., 1.])

Variable: _AGEG5YR
Description: Fourteen-level age category
    
   1 -> Age 18 to 24
   2 -> Age 25 to 29
   3 -> Age 30 to 34
   4 -> Age 35 to 39
   5 -> Age 40 to 44
   6 -> Age 45 to 49
   7 -> Age 50 to 54
   8 -> Age 55 to 59
   9 -> Age 60 to 64
   10 -> Age 65 to 69
   11 -> Age 70 to 74
   12 -> Age 75 to 79
   13 -> Age 80 or older
   14 -> Don’t know/Refused/Missing
    
Dropping 14

In [30]:
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected._AGEG5YR != 14]
brfss_2013_df_selected._AGEG5YR.unique()

array([ 9.,  8., 10.,  4.,  7.,  6.,  5., 11.,  3.,  1., 12., 13.,  2.])

Variable: EDUCA
Description: What is the highest grade or year of school you completed?
    
   1 -> Never attended school or only kindergarten
   2 -> Grades 1 through 8 (Elementary)
   3 -> Grades 9 through 11 (Some high school)
   4 -> Grade 12 or GED (High school graduate)
   5 -> College 1 year to 3 years (Some college or technical school)
   6 -> College 4 years or more (College graduate)
   9 -> Refused
    
Dropping 9

In [31]:
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.EDUCA != 9]
brfss_2013_df_selected.EDUCA.unique()

array([6., 4., 5., 2., 3., 1.])

Variable: INCOME2
Description: Is your annual household income from all sources:
    
   1 -> Less than $10,000
   2 -> Less than $15,000 ($10,000 to less than $15,000)
   3 -> Less than $20,000 ($15,000 to less than $20,000)
   4 -> Less than $25,000 ($20,000 to less than $25,000)
   5 -> Less than $35,000 ($25,000 to less than $35,000)
   6 -> Less than $50,000 ($35,000 to less than $50,000)
   7 -> Less than $75,000 ($50,000 to less than $75,000)
   8 -> $75,000 or more
   77 -> Don't know/Not sure
   99 -> Refused
    
Dropping 77 and 99

In [32]:
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.INCOME2 != 77]
brfss_2013_df_selected = brfss_2013_df_selected[brfss_2013_df_selected.INCOME2 != 99]
brfss_2013_df_selected.INCOME2.unique()

array([7., 8., 6., 4., 5., 3., 1., 2.])

In [33]:
brfss_2013_df_selected.shape

(163338, 26)

In [34]:
brfss_2013_df_selected.head()

,CVDINFR4,CVDCRHD4,_RFHYPE5,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,DIABETE3,_TOTINDA,ALCDAY5,AVEDRNK2,HLTHPLN1,MEDCOST,GENHLTH,MENTHLTH,PHYSHLTH,SEX,_AGEG5YR,EDUCA,INCOME2,_STATE,_MICHD,DROCDY3_,_DRNKWEK,_RFDRHV5
0,2.0,7.0,1.0,1.0,1.0,39.0,1.0,0.0,0.0,0.0,201.0,2.0,1.0,0.0,4.0,29.0,30.0,0.0,9.0,6.0,7.0,1.0,0,900.0,12600.0,1.0
2,2.0,2.0,0.0,0.0,0.0,27.0,1.0,0.0,0.0,0.0,220.0,4.0,1.0,0.0,3.0,2.0,3.0,0.0,8.0,6.0,8.0,1.0,0,900.0,25200.0,1.0
3,2.0,2.0,0.0,1.0,1.0,22.0,0.0,0.0,0.0,1.0,208.0,2.0,1.0,0.0,2.0,0.0,2.0,0.0,9.0,4.0,7.0,1.0,0,900.0,12600.0,1.0
4,2.0,2.0,1.0,0.0,1.0,36.0,1.0,0.0,0.0,0.0,210.0,2.0,1.0,0.0,3.0,2.0,10.0,1.0,10.0,6.0,6.0,1.0,0,900.0,12600.0,1.0
8,2.0,2.0,0.0,1.0,1.0,30.0,0.0,0.0,0.0,1.0,101.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,7.0,6.0,8.0,1.0,0,900.0,6300.0,1.0

In [35]:
brfss_2013_df_selected.groupby(['_MICHD']).size()

_MICHD
0    159818
1      3520
dtype: int64

In [36]:
brfss_2013_df_selected.groupby(['DIABETE3']).size()

DIABETE3
0.0    147089
1.0      2449
2.0     13800
dtype: int64

In [37]:
#Rename the columns to make them more readable
brfss_2013_df_selected.rename(columns = {'_MICHD':'HeartDiseaseorAttack', 
                                         '_RFHYPE5':'HighBP',  
                                         'TOLDHI2':'HighChol', '_CHOLCHK':'CholCheck', 
                                         '_BMI5':'BMI', 
                                         'SMOKE100':'Smoker', 
                                         'CVDSTRK3':'Stroke', 'DIABETE3':'Diabetes', 
                                         '_TOTINDA':'PhysActivity',
                                         '_RFDRHV5':'HvyAlcoholConsump', 
                                         'HLTHPLN1':'AnyHealthcare', 'MEDCOST':'NoDocbcCost', 
                                         'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 
                                         'SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME2':'Income',
                                         '_STATE':'State', 'CVDINFR4':'HeartAttack', 'CVDCRHD4':'CoronaryHeartDisease',
                                         'ALCDAY5':'AtLeastOneDrinkPerWeekOrMonth', 'AVEDRNK2':'AvgDrinkPerDayInLastMonth',
                                         'DROCDY3_':'DrinkOccasionsPerDay', '_DRNKWEK':'DrinksPerWeek'
                                        }, inplace=True)

In [38]:
brfss_2013_df_selected.to_csv('2013cleaneddata.csv', sep=",", index=False)